### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Dev/website-site-ng#41]
This is a list of what we need to do

### Higher priority - 优先事项

-  [x] Requirement evaluation / 产品需求分析 [REQUIREMENT.md](REQUIREMENT.md)
-  [x] Visual design and evaluation / 视觉设计及评审 `Branch design-axionl: *.ai / *.muse`
-  [x] Writing documents about implementation details / 书写设计细节文档
-  [x] Coding guidelines / 代码规范 [CONTRIBUTING.md](CONTRIBUTING.md)
-  [x] Backend / 后端构建 `app.js & /controller/*`
-  [x] Frontend templates / 前端母版框架构建
-  [X] Frontend views and pages / 前端单独页面实现
  - [x] Home
  - [x] News
  - [X] Community
  - [X] Project
  - [X] About
  - [x] Download
  - [x] News 长消息二级页面模板
  - [X] Project Templates / 项目页面模板
-  [ ] PC frontend code proofread 前端 PC 端代码审查
-  [ ] Mobile frontend / 移动端响应式处理
  - [ ] Template / 母版
  - [ ] Home
  - [ ] News
  - [ ] Project
  - [ ] About
  - [ ] Download
  - [ ] News 长消息二级页面模板
  - [ ] Project Template 项目页面模板
-  [ ] Mobile frontend code proofread 响应式处理代码审查
-  [ ] Coloring evaluation 配色再调整
-  [ ] Overall re-evaluation 整体评审

### Lower priority - 次要事项

-  [ ] RSS Feed / RSS 订阅
-  [ ] GitHub Webhook 对接
-  [ ] i18n support 多语言支持 [WIP]
-  [x] Banner background 选用横幅背景图
-  [ ] Automatic theme switch 自动切换的夜间模式
-  [ ] ABBS integration / ABBS 对接

**Comment by liushuyu** [comment]
[WIP] i18n basic support in #40

**Comment by liushuyu** [comment]
[WIP] Dependencies monitoring in #42

**Comment by liushuyu** [comment]
[WIP] Test framework in #43

**Comment by LionNatsu** [comment]
TODO: Error message pages. 4xx, 5xx etc.

**Comment by liushuyu** [comment]
@LionNatsu So mocha test is good to merge ?

**Comment by LionNatsu** [comment]
Would you like to give a description of Mocha to me in some brief sentences?
I'm not very clearly understand the relationship between Travis-CI and Mocha, and the status about them in this project now due to my such long time have not been exposed to this. My apologies.

**Comment by LionNatsu** [comment]
And @axionl and I are now ready to redesign and/or refactor (I believe it will not be redesigned  _ab-initio_) this. How do you think of the plan of CI/testing system (such as this issue)? Will you modify after redesigning?

**Comment by liushuyu** [comment]
>Would you like to give a description of Mocha to me in some brief sentences?
I'm not very clearly understand the relationship between Travis-CI and Mocha, and the status about them in this project now due to my such long time have not been exposed to this. My apologies.

There's no relationship between Travis-CI and Mocha. They're independent and I just happened to use them together. The Travis-CI is a service provides sandboxes/virtual machines/containers for developers to test their projects in real-time (ah, maybe not). And Mocha is just a multi-functional Javascript unit testing framework. And what I have done was I combined these two mechanisms together: each `push` event will trigger a Travis CI build, which will utilize the Mocha tests I've written and check for problems. The default action is to send emails to everyone who own this repository if test fails. My original hope was to ease the collaborators and just leave the simple test task to an alien machine (Travis CI Builder in this case).

>And @axionl and I are now ready to redesign and/or refactor (I believe it will not be redesigned  _ab-initio_) this. How do you think of the plan of CI/testing system (such as this issue)? Will you modify after redesigning?

I think a CI system is necessary -- unless you're 100% sure about your coding ;-)
Of course some parts of the test will be modified to match your changes.

I hope I have stated your questions clearly. If any further questions, don't hesitate to leave a comment here.

**Comment by LionNatsu** [comment]
Oh, brilliant. Yes, of course, CI system is necessary and also unit tests are necessary. Thanks!

**Comment by liushuyu** [comment]
>[WIP] Test framework in #43

Finished

>[WIP] Dependencies monitoring in #42

Finished

**Comment by liushuyu** [comment]
> RSS Feed / RSS 订阅

Finished in d3d4941c12c00a50eeb2e02bf7a16403e1f9c0d7

**Comment by liushuyu** [comment]
>GitHub Webhook 对接

@MingcongBai so consider drop this one?

**Comment by MingcongBai** [comment]
Could use this for security advisories, but it may require more detailed security-related issues.

But for pakreqs we are moving to @gumblex 's packages site, which should be going online soon.
